src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/Report.java
src/main/resources/org/jpeek/metrics/LCOM2.xsl
src/main/resources/org/jpeek/metrics/LCOM3.xsl
src/test/java/org/jpeek/MetricsTest.java

as per #92 
**LCOM2**:
> LCOM2 is an attempt to address some shortcomings of the
original LCOM:
- LCOM gives a value of zero for very different classes
- Its definition is based on method-data interaction, which may not
be a correct way to define cohesiveness in the object-oriented world
- Very different classes may have an equal value
- As LCOM is defined on variable access, it's not well suited for
classes that internally access their data via properties
LCOM2 equals the percentage of methods that do not access a specific
attribute averaged over all attributes in the class. If the number
of methods or attributes is zero, LCOM2 is undefined and displayed
as zero. Values for LCOM2 are in the range [0, 1]. A low value indicates
high cohesion and a well-designed class. It is likely that the …

#92 LCOM2/3 via XML

---

src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/Main.java
src/test/java/org/jpeek/MainTest.java

as per #104 
Note:
I moved the `Files.exist(target)` check from `App.analyze()` to `Main.run()` because I didn't want to pollute `App` with this miscellaneous parameter and just wanted to let `App.analyze()` to focus on doing the *analysis*.

(#104) Make an option to rewrite JPeek's target directory if exists

---

src/test/java/org/jpeek/MetricsTest.java

Solution for #125
Given that
> The values for LCOM5 are defined in the real interval [0, 1] where '0' describes "perfect cohesion" and '1' describes "no cohesion".
the value `0.8125d` looks believable. Before fixing #114 it was over `1.0d` which contradicts the LCOM5 definition.

(#125) Enable Bar test for LCOM5

---

README.md
src/test/java/org/jpeek/MetricsTest.java

As per #138:
Turns out that we *cannot* test LCOM2/3 against `Bar` because the compiler optimizes the bytecode by inlining the value of `Bar.NAME` inside the `Bar.getKey()` method. Therefore, the README was updated with a new section **Known Limitations** documenting this shortcoming.
For further details please see comments starting [here](https://github.com/yegor256/jpeek/issues/138#issuecomment-366548476)

(#138) Added documentation in README for known limitations

---

src/test/java/org/jpeek/MetricsTest.java

As per #124 
LCOM5 for [OneVoidMethodWithoutParams][OneVoidMethodWithoutParams.java] will not be `NaN`. According to [LCOM5.xsl][LCOM5.xsl] the value will be `NaN` only when the class has 1 method. The Skeleton treats the constructor of the class as a method, so [OneVoidMethodWithoutParams][OneVoidMethodWithoutParams.java] has in fact two methods.
**UPD.** Same goes for [OneMethodCreatesLambda][OneMethodCreatesLambda.java] for the same reason
[LCOM5.xsl]: https://github.com/yegor256/jpeek/blob/bdacc739c3660720f3bbb2a1fbf23f236f117030/src/main/resources/org/jpeek/metrics/LCOM5.xsl
[OneVoidMethodWithoutParams.java]: https://github.com/yegor256/jpeek/blob/bdacc739c3660720f3bbb2a1fbf23f236f117030/src/test/resources/org/jpeek/samples/OneVoidMethodWithoutParams.java …

(#124) LCOM5 tests

---

src/main/resources/org/jpeek/metrics/LCC.xsl

As per #119
The assumption made in #119 is absolutly incorrect. Changes made in #106 are not needed to calculate `indirectly-related-pairs`. See section 3.1 of https://pdfs.semanticscholar.org/672e/de6e3e600eafd84036a0b983b88e481ac626.pdf. The key sentence is
> The indirect connection relation is the **transitive closure** of direct connection relation
See https://en.wikipedia.org/wiki/Transitive_closure for more info on what is a Transitive Closure. Basically, if you have a graph of relationships define by adjacency pairs:
```
graph:
a - b
b - c
b - d
c - e
```
that looks like this:
```
c--e
/
a--b
\
d
```
A transitive closure of that graph is simply an extention of adjacency pairs list with transitively reachable verticies:
```
graph:
// original pairs
a - b
b - c
b - d
c - e
// …
```

(#119) LCC and Transitive Closures

---

src/main/resources/org/jpeek/metrics/MWE.xsl

as per #145:
This PR:
Implements calculation of `Di` by using [`http://www.w3.org/2005/xpath-functions/math`](https://www.w3.org/2005/xpath-functions/math/) which was introduced in XPATH/XQuery 3.1, both implemented in [our version of Saxon](http://saxon.sourceforge.net/#F9.8HE).

(#145) MWE: implemented calculation of Di

---

src/main/resources/org/jpeek/metrics/CCM.xsl
src/test/java/org/jpeek/MetricsTest.java

Issue #147
For CCM, the following test cases need to be added: NoMethods, WithoutAttributes, OneMethodCreatesLambda, OneVoidMethodWithoutParams. The CCM value for these cases is NaN.

#147 For CCM, the following test cases need to be added

---

src/main/resources/org/jpeek/metrics/CCM.xsl
src/test/java/org/jpeek/MetricsTest.java
src/test/resources/org/jpeek/samples/TwoCommonMethods.java

**Issue #149**
CCM.xsl:63-67
For CCM, need to add OR condition to the following xsl:if to check whether two methods both call another method in common for the same class. The skeleton currently does not produce this information. After this is done, we can add test cases for Foo, OverloadMethods, and TwoCommonAttributes.

#149 For CCM, need to add OR condition to the following xsl

---

src/test/java/org/jpeek/skeleton/SkeletonTest.java
src/test/resources/org/jpeek/samples/ClassAccessingPublicField.java
src/test/resources/org/jpeek/samples/ClassWithPublicField.java

For #156:
- created classes `ClassWithPublicField` and `ClassAccessingWithPublicField` to emulate the desired scenario;
- created test in `SkeletonTest` for testing if the `Skeleton` class is behaving like intended;
- left `@todo` in `SkeletonTest` for upgrade existing `Skeleton` implementation.

#156: Determining if Skeleton is accessing same class or another class.

---

src/test/java/org/jpeek/MetricsTest.java

To fix the problem it's enough to specify the US locale in String.format() method inside assertThat()

#246: internalization problem in numeric tests fixed

---

src/main/java/org/jpeek/Matrix.java
src/main/resources/org/jpeek/xsd/matrix.xsd
src/test/java/org/jpeek/MatrixTest.java

This PR (#225).
- adds a new test case xmlHasSchema that checks whether the matrix.xml has a schema reference
- implements adding of the schema reference to the matrix.xml
- minor MatrixTest refactoring ("matrix.xml" is stored as a class constant now)

(#225) Added a matrix.xsd reference to matrix.xml

---

src/main/resources/org/jpeek/metrics/LORM.xsl
src/test/java/org/jpeek/MetricsTest.java
src/test/java/org/jpeek/metrics/LormTest.java
src/test/java/org/jpeek/metrics/package-info.java

Currently, LORM metric is not implemented and not tested
although it seems to do something but definitely doesn't do what's
described in the paper and claimed in the description : (LORM = (R /
RN) where RN = N * (N - 1) / 2, N = total number of methods, R - method
relationships)
This PR:
- adds two unit tests for LORM: one as a parameter to the common
MetricsTest, another one for the specific metric LormTest
- implements the LORM metric according to the paper and the description

Implement LORM as described

---

src/test/java/org/jpeek/MetricsTest.java

This is the fix for #181. Because of `@Parameterized` already introduced I've just removed the todo.

#181 Remove todo because the issue is already fixed.

---

pom.xml

The following dependencies were breaking build on Java versions higher than 7:
- org.ow2.asm:asm:6.0 – broke on Java 8 and Java 11 (tested with Oracle JDK 1.8.0_231, OpenJDK 11.0.5), upgraded to 6.2.1 (latest 6.x version, assuming Semantic Versioning is in effect)
- org.jacoco:jacoco-maven-plugin:0.7.8 – broke on Java 11 (tested with OpenJDK 11.0.5), upgraded to 0.8.5 (latest current version, since all 0.7.x versions break on Java 11 as well)

(#272) Update dependencies for Java 8+ support

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

#312 
- updated the PULL_REQUEST_TEMPLATE 
**Following new rules  are added**
- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

#312 Update PR guidelines in PULL_REQUEST_TEMPLATE

---

pom.xml

This PR is related to issue #324 and allows incremental compilation for `maven-compiler-plugin` adding appropriate plugin key into `pom.xml`

Update maven-compiler-plugin to 3.8.0

---

README.md

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).
This …

valid maven repo link

---

.travis.yml
src/main/java/org/jpeek/Report.java

Ressolving issue #355 
Travis lacks pdd checks.
The PR consists of ~3~ 4 commits:
* 23bdbd7 and 1e082eb : add badly worded puzzle -> we see here that travis accepts it
* 8c1337c : fix travis build script -> Travis is now failing
* cd51569 : remove the badly worded puzzle introduced in 23bdbd7 and 1e082eb, so everything is back to normal

#355 Add puzzles check on travis

---

src/test/java/org/jpeek/metrics/Lcom4Test.java
src/test/java/org/jpeek/metrics/LormTest.java
src/test/java/org/jpeek/package-info.java
src/test/java/org/jpeek/skeleton/SkeletonTest.java
src/test/java/org/jpeek/skeleton/TypesOfTest.java
src/test/java/org/jpeek/skeleton/XmlClassTest.java

Resolving puzzle #380 
Migrate tests on 2 packages.
Update the puzzle to:
* include only the last package to migrate
* once completed, remove junit-vintage-engine dependency
* optionally/ideally find a way to exclude junit 4 dependency.

resolve puzzle #380 migrate tests to junit 5

---

src/main/java/org/jpeek/Report.java

Adding a puzzle to continue resolving #296

#296 add a puzzle for a java implementation

---

src/test/java/org/jpeek/web/ReportsTest.java

Resolving issue #386 
We are migrating to junit 5 anyway.
Used Junit 5 tempdir that is automatically deleted after test by junit.

#386 using junit 5 tempdir

---

src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/Calculus.java
src/main/java/org/jpeek/XslCalculus.java
src/main/java/org/jpeek/XslReport.java
src/test/java/org/jpeek/MetricsTest.java
src/test/java/org/jpeek/XslCalculusTest.java
src/test/java/org/jpeek/XslReportTest.java

Resolving #390.  The main idea is to separate report generation from metrics calculation. Finally, I chose to keep Xsl report as an xsl implementation for report generation. This is easier to continue to have statistics and post processing. But now, Xsl report is delegating metrics calculation to a new `Calculus` interface. `Calculus` interface implementation are supposed to produce an XML with the metrics calculation. Mainly, this PR:
* Refactors XslReport to separate metrics calculation concern, from post-processing and writing reports to disk concern
* Refactor tests accordingly
* Add a puzzle to have a Java calculus implementation for LCOM4

#390 refactor and separate report generation from calculus

---

src/main/resources/org/jpeek/metrics/TCC.xsl
src/test/java/org/jpeek/MetricsTest.java
src/test/resources/org/jpeek/samples/ClassSameAsAnotherPublicField.java

Resolving issue #195 
`$attrs` xslt variable on which we test and filter already takes attributes in skeleton that:
* are not static (so the problem in #156 can not happen)
* in skeleton ops/op text content already has the fully qualified name when it comes to other classes static fields
Added a test case to ensure this.

#195 Add a test case

---

src/main/java/org/jpeek/graph/Graph.java
src/main/java/org/jpeek/graph/Node.java
src/main/java/org/jpeek/graph/XmlGraph.java
src/main/java/org/jpeek/graph/package-info.java
src/test/java/org/jpeek/graph/NodeSimpleTest.java
src/test/java/org/jpeek/graph/XmlGraphTest.java
src/test/java/org/jpeek/graph/package-info.java

Resolving issue #397 
Starting graph construction infrastructure.

#397 Graph infrastructure

---

src/main/resources/org/jpeek/metrics/TCC.xsl
src/test/resources/org/jpeek/metricstest-params.csv

Resolving issue #213 
* Force TCC value to 1 if no attributes or if it has less or equal to 1 method.
* Fix WithoutAttributes test value to 1
* Add a test case for no methods.

#213 fix TCC metric for no methods or no attributes

---

.rultor.yml

For #406 - returning to java 8 docker image, jpeek is incompatible with java 11

For #406 - returning to java 8

---

src/main/java/org/jpeek/graph/Disjoint.java
src/test/java/org/jpeek/graph/DisjointTest.java
src/test/java/org/jpeek/metrics/Lcom4Test.java

Resolving #415 
Graph disjoint sets implementation.

#415 disjoint sets impl

---

pom.xml
src/main/java/org/jpeek/web/Dynamo.java

This is for #313.
According to jcabi changelog, this was fixed since 0.49.2 (most certainly with 0.49.5 but changelog is not extremely clear).
Since
- 0.49.2 was released before #313 was opened
- 0.49.9 was released after #313 was opened
I believe this should be alright to answer the ticket submitter request for using latest snapshot at the time.

#313 bump jcabi parent version to 0.49.9

---

src/main/java/org/jpeek/skeleton/OpsOf.java
src/main/resources/org/jpeek/xsd/skeleton.xsd
src/test/java/org/jpeek/skeleton/SkeletonTest.java

[#403](https://github.com/yegor256/jpeek/issues/403)

403: Skeleton should reflect the exact overloaded called method

---

src/main/java/org/jpeek/graph/XmlGraph.java
src/test/java/org/jpeek/graph/XmlGraphTest.java

Resolving issue #413 
Add a puzzle to reenable tests after #437 is resolved.

#413 support overloading in graph construction

---

src/main/java/org/jpeek/graph/XmlMethodCall.java
src/test/java/org/jpeek/graph/XmlMethodCallTest.java

PR for #443 
I made the `XmlMethodCall` public and added a test. N.B. The "call" elements in skeleton don't have the structure expected in the test, but it will be implemented in https://github.com/yegor256/jpeek/issues/437.

Made XmlMethodCall public and added a test.

---

README.md
src/main/java/org/jpeek/App.java

For #452: 
- Added `LCOM4` report to `Main.java`
- Left puzzle to document better jPeek usage on `README.md`

For #452: Added LCOM4 report

---

.rultor.yml

Last lines of `434aa056` rultor release execution are failing due to a `settings.xml` file left on the repository, because the reset command is not being executed when there is a failure to push the repository to dokku.
```
+ rm -rf /home/r/.ssh
+ mkdir /home/r/.ssh
+ mv ../id_rsa ../id_rsa.pub /home/r/.ssh
+ chmod 600 /home/r/.ssh/id_rsa /home/r/.ssh/id_rsa.pub
+ echo -e 'Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null'
+ git remote add dokku dokku@dokku.jpeek.org:jpeek
+ git add settings.xml
+ git commit -m settings.xml
[__rultor a153e96] settings.xml
1 file changed, 33 insertions(+)
create mode 100644 settings.xml
++ git symbolic-ref --short HEAD
+ git push -f dokku __rultor:master
Warning: Permanently added 'dokku.jpeek.org,178.238.236.225' (ECDSA) to the list of …
```

For #465: split dokku repository reset

---

src/main/java/org/jpeek/graph/XmlGraph.java
src/main/java/org/jpeek/graph/XmlMethodArgs.java
src/main/java/org/jpeek/graph/XmlMethodCall.java
src/main/java/org/jpeek/graph/XmlMethodSignature.java
src/test/java/org/jpeek/graph/XmlMethodSignatureTest.java

PR for https://github.com/yegor256/jpeek/issues/445
Extracted a new class. Also noticed a possibility to modify another so it could be reused. That solved the issue of a disabled test which I re-enabled and removed the corresponding `todo`.

#445 - Extracted a new class and modified another to make it reusable.

---

src/main/java/org/jpeek/graph/XmlGraph.java

This is for #472. 
The changes are small, but I verified that:
- all the tests were present
- there was no more things to extract from the class
- that it didn't make sense to transform the build method into a class because we would end up with two classes, one for `XmlGraph` just delegating to the second, and the second very similar to `XmlGraph` as it is currently written.
It also gave me the opportunity to understand what the code was doing, and I opened a few issues in cactoos and jpeek.

(#472) - Remove checkstyle suppression

---

src/main/resources/org/jpeek/metrics/LORM.xsl
src/test/java/org/jpeek/metrics/LormTest.java

PR for #470 
Fixed the XSL to work with new skeleton structure and re-enabled the test.

#470 - Fixed LORM XSL.

---

src/main/java/org/jpeek/calculus/Calculus.java
src/main/java/org/jpeek/calculus/java/Ccm.java

#449 
To calculate NCC correctly, we will use Java `Graph` instead of XSL. This PR introduces Java based CCM Calculus and adds `todo`s for further work.

#449 - Begin Java CCM.

---

src/main/java/org/jpeek/graph/XmlGraph.java
src/main/java/org/jpeek/graph/XmlMethodArgs.java
src/main/java/org/jpeek/graph/XmlMethodCall.java
src/test/java/org/jpeek/graph/XmlGraphTest.java

#473 
Made XmlGraph specific to a particular class inside a skeleton.

#473 - Specify which class the graph is for.

---

README.md

I've added a toggle-table with a list of all CLI options (parameters) I've found in the `src/main/java/org/jpeek/Main.java`.
Closes #460, closes #494

add available CLI options to README.md

---

src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/Metrics.java
src/test/java/org/jpeek/MainTest.java

resolution of issue https://github.com/cqfn/jpeek/issues/461
Extracted part of App.analyze method, which responsible for building report into separate method App.buildReport.
To make code simplier, added enum that represents Metrics and their meta-information.

Extracting report build into separate method

---

src/test/java/org/jpeek/skeleton/SkeletonTest.java
src/test/java/org/jpeek/skeleton/TypesOfTest.java

Fixed warnings in Skeleton test appearing during clean install: "the keyword return in this context means child::return"

Fixed some warnings, appearing during clean install

---

.github/workflows/mvn.yml
pom.xml
src/test/java/org/jpeek/metrics/CcmTest.java
src/test/resources/org/jpeek/samples/CcmManyComp.java
src/test/resources/org/jpeek/samples/CcmManyCompWithCtor.java
src/test/resources/org/jpeek/samples/CcmMixCallManyComp.java
src/test/resources/org/jpeek/samples/CcmOneComp.java

- disabled test with manually calculated ccm (and all parts)
- one more issue for nc calculation
- update jacoco plugin (0.8.8 produce a error on jdk 17+)
- limit mvn job execution to 1 hour

[#522] Tests for CCM calculations

---

src/test/java/org/jpeek/metrics/CcmTest.java
src/test/resources/org/jpeek/samples/CcmManyCompWithCtor.java
src/test/resources/org/jpeek/samples/CcmOneComp.java

constructor in src/test/resources/org/jpeek/samples/CcmManyCompWithCtor.java had incorrect name, so the test that used that file was buggy.

Ccm constructor

---

src/main/resources/org/jpeek/metrics/TLCOM.xsl
src/test/resources/org/jpeek/metricstest-params.csv

@yegor256 here is the issue #501 fixed
I added the missing test and checked its correctness. Now there is a test that checks the value of the TLCOM metric for the OneMethodCreatesLambda class

fixed issue 501

---

src/test/java/org/jpeek/web/FuturesTest.java

Added test for `asString` method.

Improve Futures class code coverage 

---

src/main/java/org/jpeek/web/Futures.java
src/test/java/org/jpeek/web/FuturesTest.java

Fix for the issue mentioned in #564. I made sure that the ordering of group and artifact variables is consistent.

Fix the ordering of group and artifact variables

---

src/test/java/org/jpeek/AppTest.java

Previously, only the  `include-private-methods` flag was tested. I added the `include-static-methods` and `include-ctors` flags to the test. The same thing could be achieved by adding two tests, one for each of the flags, but I decided against this as it would add a lot of duplicate code.

Extend the App.java test
