cqfn/jpeek

src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/metrics/cohesion/NHD.java
src/test/java/org/jpeek/metrics/cohesion/NHDTest.java

NHD Metric Implementation

---

README.md
src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/metrics/cohesion/LCOM2.java
src/main/java/org/jpeek/metrics/cohesion/LCOM3.java
src/test/java/org/jpeek/metrics/cohesion/LCOM2Test.java
src/test/java/org/jpeek/metrics/cohesion/LCOM3Test.java
src/test/resources/org/jpeek/WithoutAttributes.java

LCOM2 and LCOM3 Implementation

LCOM2-3 Impl

---

src/main/java/org/jpeek/App.java
src/main/resources/org/jpeek/metrics/MMAC.xsl
src/test/java/org/jpeek/MetricsTest.java

XML/XSL implementation of MMAC metric, based on Java implementation in #14

#91 implement MMAC via XML/XSL

---

src/main/java/org/jpeek/App.java
src/main/resources/org/jpeek/metrics/LORM.xsl

#15 LORM was introduced

---

src/main/java/org/jpeek/App.java
src/main/resources/org/jpeek/metrics/MWE.xsl

Fix for #17 
http://www.cs.wm.edu/~denys/pubs/ICSM09-LDA-cohesion.pdf

#17 MWE metric introduced

---

src/main/resources/org/jpeek/xsd/index.xsd
src/main/resources/org/jpeek/xsd/matrix.xsd
src/main/resources/org/jpeek/xsd/metric.xsd
src/main/resources/org/jpeek/xsd/skeleton.xsd

(#134) Documented skeleton.xsd

---

src/main/java/org/jpeek/App.java
src/main/resources/org/jpeek/metrics/LCC.xsl
src/main/resources/org/jpeek/metrics/TCC.xsl
src/test/java/org/jpeek/MetricsTest.java

For #118
**Issue**
LCC metric has impediments. Need to wait for resolving these impediments, add LCC to reports list and cover it by tests.

#118 LCC metric has impediments

---

src/main/java/org/jpeek/App.java

**Issue #146**
Add the CCM metric report here when all the puzzles about it are resolved.

#146 Add the CCM metric report here

---

src/main/java/org/jpeek/web/Reports.java

PR for #151 
Added an existance verification of the file "/dev/null". If it exists then it is created, otherwise it is created the file "NUL" , Windows compatible version.

Added check if file exists

---

src/main/java/org/jpeek/App.java
src/main/java/org/jpeek/skeleton/XmlClass.java
src/main/resources/org/jpeek/metrics/LCOM2.xsl
src/main/resources/org/jpeek/metrics/MWE.xsl
src/main/resources/org/jpeek/xsd/skeleton.xsd
src/test/java/org/jpeek/MetricsTest.java
src/test/resources/org/jpeek/samples/BridgeMethod.java

**Issue #171**
Solves #171: Ignore bridge methods
The metric LCOM2 should ignore bridge methods

#171: Ignore bridge methods

---

src/main/java/org/jpeek/FileTarget.java
src/main/java/org/jpeek/Main.java
src/main/java/org/jpeek/Target.java

PR for #154. Refactored the very procedural logic for overwriting the target directory.
Created a Target interface and FileTarget for that.

Refactored the very procedural logic for overwriting the target directory

---

src/main/java/org/jpeek/App.java

Remove the puzzle for #146.
The metric report was added in #249.

#146 - Remove puzzle from #66

---

README.md
src/test/java/org/jpeek/MetricsTest.java

#203 added more tests for OCC metric

---

.rultor.yml

Updated `rultor.yml`  with my architect info, at the moment I can't ask rultor to merge PRs

Update rultor.yml with architect info

---

README.md
src/main/resources/org/jpeek/xsd/index.xsd

I added some documentation to index.xsd.
I did not understand the bars element in time. So I left a puzzle instead.

#199 Add documentation to index.xsd

---

status-reports/2019-01-11

Project report - 2019/01/11

---

pom.xml
src/main/java/org/jpeek/Version.java
src/main/java/org/jpeek/web/Dynamo.java
src/main/java/org/jpeek/web/Futures.java
src/main/java/org/jpeek/web/TkApp.java
src/main/java/org/jpeek/web/TkIndex.java
src/main/java/org/jpeek/web/TkMistakes.java
src/main/java/org/jpeek/web/TkQueue.java

this PR upgrades cactoos dependency to 0.38

upgrade cactoos to 0.38

---

src/test/java/org/jpeek/MetricsTest.java

This PR adds the remaining test classes to the PCC test cases. #205

Implement more PCC tests #205

---

status-reports/2019-02-19.md

Status report 2019-02-19.

---

src/main/java/org/jpeek/Index.java
src/main/resources/org/jpeek/xsd/index.xsd
src/test/java/org/jpeek/IndexTest.java
src/test/java/org/jpeek/MatrixTest.java

#226 
The schema fix and a unit test for it

(#226) Index.xsd: add a reference to schema

---

README.md
src/main/java/org/jpeek/Main.java
src/test/java/org/jpeek/MainTest.java
src/test/java/org/jpeek/web/DyNumTest.java
src/test/java/org/jpeek/web/PagesTest.java

Lines covered ratio increased to 0.67.
- Fixes #320
- DyNumTest.java and PagesTest.java added to increase lines covered ratio

(#320) Fix ''Build of whole project is broken."

---

src/main/resources/org/jpeek/xsd/skeleton.xsd

Desciption:    
1. The puzzle has been removed since the issue has been done
in the pull request #339.

#224 add a reference to this schema from the generated skeleton.xml

---

src/main/resources/org/jpeek/templates.xsl
src/main/resources/org/jpeek/web/layout.xsl
src/main/resources/org/jpeek/xsl/matrix.xsl

(#315) replaced Broken RawGit links

(#315) replaced Broken RawGit links

---

forbidden-apis.txt
src/test/java/org/jpeek/AppTest.java
src/test/java/org/jpeek/DefaultBaseTest.java
src/test/java/org/jpeek/IndexTest.java
src/test/java/org/jpeek/MainTest.java
src/test/java/org/jpeek/MatrixTest.java
src/test/java/org/jpeek/MetricsTest.java
src/test/java/org/jpeek/ReportTest.java
src/test/java/org/jpeek/ReportWithStatisticsTest.java
src/test/java/org/jpeek/skeleton/SkeletonTest.java
src/test/java/org/jpeek/skeleton/TypesOfTest.java
src/test/java/org/jpeek/skeleton/XmlClassTest.java
src/test/java/org/jpeek/web/AsyncReportsTest.java
src/test/java/org/jpeek/web/MistakesTest.java
src/test/java/org/jpeek/web/ReportsTest.java
src/test/java/org/jpeek/web/ResultsTest.java
src/test/java/org/jpeek/web/TkAppTest.java
src/test/java/org/jpeek/web/TkIndexTest.java
src/test/java/org/jpeek/web/TkMistakesTest.java

`assertThat` was replaced to `Assertion`

#309 Add support to cactoos-matchers

---

src/main/java/org/jpeek/skeleton/XmlClass.java
src/main/resources/org/jpeek/xsd/skeleton.xsd
src/main/resources/org/jpeek/xsl/layers/no-private-methods.xsl
src/test/java/org/jpeek/AppTest.java
src/test/java/org/jpeek/skeleton/SkeletonTest.java
src/test/java/org/jpeek/skeleton/XmlClassTest.java

#297 attribute public removed from method tag

#297 skeleton.xsd:31-33: Skeleton.xsd: remove method/@public.... 

---

status-reports/2019-12-05.md

Status report 2019-12-05

---

src/test/java/org/jpeek/skeleton/ClassAsXml.java
src/test/java/org/jpeek/skeleton/XmlClassTest.java
src/test/java/org/jpeek/web/ReportsTest.java

The 3th PR attempt with Qulice checks satisfaction

Class as xml externalization

---

.rultor.yml
src/main/java/org/jpeek/web/Reports.java

For #373: Updating rultor image

For #373: Updating rultor image

---

src/test/java/org/jpeek/skeleton/SkeletonTest.java

Remove the stale puzzle [#358](https://github.com/yegor256/jpeek/issues/358)

remove the stale puzzle

---

pom.xml
src/test/java/org/jpeek/AppTest.java
src/test/java/org/jpeek/DefaultBaseTest.java
src/test/java/org/jpeek/IndexTest.java
src/test/java/org/jpeek/MainTest.java
src/test/java/org/jpeek/MatrixTest.java
src/test/java/org/jpeek/MetricsTest.java
src/test/java/org/jpeek/ReportTest.java
src/test/java/org/jpeek/ReportWithStatisticsTest.java
src/test/java/org/jpeek/package-info.java

Resolving issue #323 
Added two puzzles:
* migrate parametrized `MetricsTest` test
* continue to migrate test in other packages

#323 Migration to JUnit 5

---

src/main/java/org/jpeek/App.java

Resolving issue #253 
This puzzle was first added in #9 
It was transformed as an issue by pdd as per #118 
#118 has two merged pull requests:
* #231 that reported the puzzle again and did not add LCC report to App
* #242 that added LCC to the list of reports but did not remove the puzzle

#253 remove resolved puzzle

---

src/test/java/org/jpeek/MetricsTest.java
src/test/java/org/jpeek/package-info.java
src/test/java/org/jpeek/web/AsyncReportsTest.java
src/test/java/org/jpeek/web/DyNumTest.java
src/test/java/org/jpeek/web/FuturesTest.java
src/test/java/org/jpeek/web/MistakesTest.java
src/test/java/org/jpeek/web/PagesTest.java
src/test/java/org/jpeek/web/ReportsTest.java
src/test/java/org/jpeek/web/ResultsTest.java
src/test/java/org/jpeek/web/TkAllTest.java
src/test/java/org/jpeek/web/TkAppTest.java
src/test/java/org/jpeek/web/TkIndexTest.java
src/test/java/org/jpeek/web/TkMistakesTest.java
src/test/java/org/jpeek/web/TkReportTest.java
src/test/java/org/jpeek/web/TkUploadTest.java

#388 migrate org.jpeek.web to junit 5

---

src/main/java/org/jpeek/web/Reports.java

https://github.com/yegor256/jpeek/issues/368
Added extracting classes from Jar file using java API

#368 Test org.jpeek.web.ReportsTest#rendersOneReport is unstable

---

pom.xml

For #406: fixing rultor release

For #406: fixing rultor release

---

.rultor.yml

For #406: changing rultor image
Added rultor image to rultor.yml

For #406: changing rultor image

---

.rultor.yml

For #460: changing rultor image to g4s8/rultor:alpine3.10

For #460: changing rultor image to g4s8/rultor:alpine3.10

---

.rultor.yml

For #406: getting rultor config from artipie

For #406: getting rultor config from artipie

---

.rultor.yml

For #406: removed JAVA_HOME wrong path

For #406: removed JAVA_HOME wrong path

---

.rultor.yml

For #406: fix rultor integration using java 8

For #406: fix rultor integration using java 8

---

.rultor.yml

For #406: fixing image permissions on java 8 - trying to execute as root

For #406: fixing image permissions on java 8

---

.rultor.yml

For #406: adding ssh installation to image

For #406: adding ssh installation to image

---

.rultor.yml

For #406: ssh confirmation

---

src/main/java/org/jpeek/graph/XmlGraph.java
src/main/java/org/jpeek/graph/XmlMethodArgs.java
src/main/java/org/jpeek/graph/XmlMethodCall.java

Transform static methods into classes

---

src/test/java/org/jpeek/graph/XmlMethodArgsTest.java

Resolving issue #444 
Added a test class with two cases, and made the class public.

#444 Test class for XmlMethodArgs

---

src/main/java/org/jpeek/skeleton/XmlClass.java
src/main/resources/org/jpeek/metrics/CCM.xsl
src/test/resources/org/jpeek/metricstest-params.csv

Resolving issue #453 
Fixed the calculation to avoid taking constructors into account.
Updates CCM metrics expectations accordingly (that normally increased)

#453 Fix ccm metrics calculation

---

src/main/java/org/jpeek/skeleton/OpsOf.java
src/main/resources/org/jpeek/xsd/skeleton.xsd
src/test/java/org/jpeek/MetricsTest.java
src/test/java/org/jpeek/metrics/LormTest.java
src/test/java/org/jpeek/skeleton/SkeletonTest.java
src/test/resources/org/jpeek/metricstest-params.csv

Resolving #437 
Skeleton structure changed, so some tests are disabled.

#437 Modify skeleton call structure

---

README.md

For #274:
- set up of jPeek maven plugin repository at https://github.com/yegor256/jpeek-maven-plugin
- added about plugin to readme

For #274: jPeek maven plugin setup

---

src/main/java/org/jpeek/graph/Node.java
src/main/java/org/jpeek/graph/XmlGraph.java
src/main/java/org/jpeek/graph/XmlMethodCall.java
src/test/java/org/jpeek/graph/XmlGraphTest.java
src/test/java/org/jpeek/graph/XmlMethodCallTest.java

PR for #441
Fixed and enabled tests, and also fixed a few other minor things.

#413 - Fixed and enabled XmlGraph tests.

---

.github/workflows/shellcheck.yml
deploy.sh
ping-all.sh
research/2018-April/04-collect-metrics/process-artifact.sh
research/2018-April/04-collect-metrics/run.sh

This PR:
- Applies fixes from the [Shellcheck](https://www.shellcheck.net/) to the existing shell scripts.
- Adds shellcheck workflow to prevent further errors.
@yegor256

Fix shell scripts, add shellcheck workflow

---

src/main/java/org/jpeek/App.java
src/main/resources/org/jpeek/xsd/matrix.xsd

resolution of https://github.com/cqfn/jpeek/issues/200
removed todo from App.java, because it was fixed in https://github.com/cqfn/jpeek/pull/544, but i forgot to remove it.

added documentation to matrix.xml.

---

pom.xml

@yegor256 ,Fixed the following [issue 475](https://github.com/cqfn/jpeek/issues/475),Could you please review it.

Fixed Small error in pom.xml

---

src/test/resources/org/jpeek/samples/CcmOneComp.java

There is a Class named ccmOneComp, while public class inside named ccmOneComponent. Fix would allow use this class in testing.

Ccm one comp fix

---

src/test/java/org/jpeek/MainTest.java

Improved `Main.java` code coverage by adding a new test for method inclusion filters.

Improve Main code coverage
